name: us-song-lyrics-sentiment
channels:
  - defaults
  - conda-forge
dependencies:
  - Sphinx
  - black
  - pandas
  - numpy
  - matplotlib
  - statsmodels
  - requests
  - seaborn
  - scikit-learn
  - beautifulsoup4
  - jupyter
  - flake8
  - wordcloud
  - fbprophet
  - python-dotenv>=0.5.1
  - pip
  - pip:
      - afinn
      - pmdarima
      - nltk
